/**
 * Dictionnaire des abréviations et structures administratives
 * Basé sur les structures réelles de la DGI du Cameroun
 * Mis à jour avec toutes les structures identifiées
 */
const abbreviations = {
    // === CENTRES D'IMPÔTS DÉPARTEMENTAUX (CDI) - Masculins ===
    'cdi': { full: 'Centre d\'Impôts Départemental', gender: 'm' },
    'cdi1': { full: 'Centre d\'Impôts Départemental 1', gender: 'm' },
    'cdi2': { full: 'Centre d\'Impôts Départemental 2', gender: 'm' },
    'cdi3': { full: 'Centre d\'Impôts Départemental 3', gender: 'm' },
    'cdi4': { full: 'Centre d\'Impôts Départemental 4', gender: 'm' },
    'cdi5': { full: 'Centre d\'Impôts Départemental 5', gender: 'm' },
    'cdi6': { full: 'Centre d\'Impôts Départemental 6', gender: 'm' },
    
    // CDI par région/localité
    'cdi mvila': { full: 'Centre d\'Impôts Départemental Mvila', gender: 'm' },
    'cdi obala': { full: 'Centre d\'Impôts Départemental Obala', gender: 'm' },
    'cdi benoue': { full: 'Centre d\'Impôts Départemental Bénoué', gender: 'm' },
    'cdi nyong et kelle': { full: 'Centre d\'Impôts Départemental Nyong et Kellé', gender: 'm' },
    'cdi moungo': { full: 'Centre d\'Impôts Départemental Moungo', gender: 'm' },
    'cdi mayo banyo': { full: 'Centre d\'Impôts Départemental Mayo Banyo', gender: 'm' },
    'cdi bafoussam': { full: 'Centre d\'Impôts Départemental Bafoussam', gender: 'm' },
    'cdi mayo sava': { full: 'Centre d\'Impôts Départemental Mayo Sava', gender: 'm' },
    'cdi mayo kani': { full: 'Centre d\'Impôts Départemental Mayo Kani', gender: 'm' },
    'cdi bonaberi': { full: 'Centre d\'Impôts Départemental Bonabéri', gender: 'm' },
    'cdi zoetele': { full: 'Centre d\'Impôts Départemental Zoétélé', gender: 'm' },
    'cdi haut nyong': { full: 'Centre d\'Impôts Départemental Haut Nyong', gender: 'm' },
    'cdi lom et djerem': { full: 'Centre d\'Impôts Départemental Lom et Djerem', gender: 'm' },
    'cdi haut plateaux': { full: 'Centre d\'Impôts Départemental Haut Plateaux', gender: 'm' },
    'cdi logone et chari': { full: 'Centre d\'Impôts Départemental Logone et Chari', gender: 'm' },
    'cdi mayo tsanaga': { full: 'Centre d\'Impôts Départemental Mayo Tsanaga', gender: 'm' },
    'cdi nyong et mfoumou': { full: 'Centre d\'Impôts Départemental Nyong et Mfoumou', gender: 'm' },
    'cdi dja et lobo': { full: 'Centre d\'Impôts Départemental Dja et Lobo', gender: 'm' },
    'cdi mefou et akono': { full: 'Centre d\'Impôts Départemental Méfou et Akono', gender: 'm' },
    'cdi vina': { full: 'Centre d\'Impôts Départemental Vina', gender: 'm' },
    'cdi mbandjock': { full: 'Centre d\'Impôts Départemental Mbandjock', gender: 'm' },
    'cdi diamare': { full: 'Centre d\'Impôts Départemental Diamaré', gender: 'm' },
    'cdi faro et deo': { full: 'Centre d\'Impôts Départemental Faro et Déo', gender: 'm' },
    'cdi mbam et inoubou': { full: 'Centre d\'Impôts Départemental Mbam et Inoubou', gender: 'm' },
    'cdi nyong et soo': { full: 'Centre d\'Impôts Départemental Nyong et So\'o', gender: 'm' },
    'cdi haute sanaga': { full: 'Centre d\'Impôts Départemental Haute Sanaga', gender: 'm' },
    'cdi mayo louti': { full: 'Centre d\'Impôts Départemental Mayo Louti', gender: 'm' },
    'cdi menoua': { full: 'Centre d\'Impôts Départemental Menoua', gender: 'm' },
    'cdi ocean': { full: 'Centre d\'Impôts Départemental Océan', gender: 'm' },
    'cdi mezam': { full: 'Centre d\'Impôts Départemental Mezam', gender: 'm' },
    'cdi mefou et afamba': { full: 'Centre d\'Impôts Départemental Méfou et Afamba', gender: 'm' },
    'cdi haut nkam': { full: 'Centre d\'Impôts Départemental Haut Nkam', gender: 'm' },
    'cdi mayo danay': { full: 'Centre d\'Impôts Départemental Mayo Danay', gender: 'm' },
    'cdi noun': { full: 'Centre d\'Impôts Départemental Noun', gender: 'm' },
    'cdi vallee du ntem': { full: 'Centre d\'Impôts Départemental Vallée du Ntem', gender: 'm' },
    'cdi sanaga maritime': { full: 'Centre d\'Impôts Départemental Sanaga Maritime', gender: 'm' },
    'cdi mbam et kim': { full: 'Centre d\'Impôts Départemental Mbam et Kim', gender: 'm' },
    'cdi boumba et ngoko': { full: 'Centre d\'Impôts Départemental Boumba et Ngoko', gender: 'm' },
    'cdi faro': { full: 'Centre d\'Impôts Départemental Faro', gender: 'm' },
    'cdi nde': { full: 'Centre d\'Impôts Départemental Ndé', gender: 'm' },
    'cdi monatele': { full: 'Centre d\'Impôts Départemental Monatélé', gender: 'm' },
    'cdi donga mantung': { full: 'Centre d\'Impôts Départemental Donga Mantung', gender: 'm' },
    'cdi momo': { full: 'Centre d\'Impôts Départemental Momo', gender: 'm' },
    'cdi bamboutos': { full: 'Centre d\'Impôts Départemental Bamboutos', gender: 'm' },
    'cdi mayo rey': { full: 'Centre d\'Impôts Départemental Mayo Rey', gender: 'm' },
    'cdi nkam': { full: 'Centre d\'Impôts Départemental Nkam', gender: 'm' },
    'cdi koung khi': { full: 'Centre d\'Impôts Départemental Koung Khi', gender: 'm' },
    'cdi mbanga': { full: 'Centre d\'Impôts Départemental Mbanga', gender: 'm' },
    'cdi meyomessala': { full: 'Centre d\'Impôts Départemental Meyomessala', gender: 'm' },
    'cdi djerem': { full: 'Centre d\'Impôts Départemental Djerem', gender: 'm' },
    'cdi saa': { full: 'Centre d\'Impôts Départemental Sa\'a', gender: 'm' },
    'cdi kadey': { full: 'Centre d\'Impôts Départemental Kadey', gender: 'm' },
    'cdi foumbot': { full: 'Centre d\'Impôts Départemental Foumbot', gender: 'm' },
    'cdi mbere': { full: 'Centre d\'Impôts Départemental Mbéré', gender: 'm' },
    'cdi boyo': { full: 'Centre d\'Impôts Départemental Boyo', gender: 'm' },
    'cdi ngoketunjia': { full: 'Centre d\'Impôts Départemental Ngoketunjia', gender: 'm' },
    'cdi menchum': { full: 'Centre d\'Impôts Départemental Menchum', gender: 'm' },
    'cdi bui': { full: 'Centre d\'Impôts Départemental Bui', gender: 'm' },
    
    // CDI Sud-Ouest
    'cdi limbe': { full: 'Centre d\'Impôts Départemental Limbé', gender: 'm' },
    'cdi meme': { full: 'Centre d\'Impôts Départemental Mémé', gender: 'm' },
    'cdi ndian': { full: 'Centre d\'Impôts Départemental Ndian', gender: 'm' },
    'cdi buea': { full: 'Centre d\'Impôts Départemental Buéa', gender: 'm' },
    'cdi tiko': { full: 'Centre d\'Impôts Départemental Tiko', gender: 'm' },
    'cdi lebialem': { full: 'Centre d\'Impôts Départemental Lebialem', gender: 'm' },
    'cdi manyu': { full: 'Centre d\'Impôts Départemental Manyu', gender: 'm' },
    'cdi bakassi': { full: 'Centre d\'Impôts Départemental Bakassi', gender: 'm' },
    'cdi muyuka': { full: 'Centre d\'Impôts Départemental Muyuka', gender: 'm' },
    'cdi kupe manenguba': { full: 'Centre d\'Impôts Départemental Kupe Manenguba', gender: 'm' },
    
    // === CENTRES D'IMPÔTS DES MOYENNES ENTREPRISES (CIME) - Masculins ===
    'cime': { full: 'Centre d\'Impôts des Moyennes Entreprises', gender: 'm' },
    'cime limbe': { full: 'Centre d\'Impôts des Moyennes Entreprises Limbé', gender: 'm' },
    'cime ngaoundere': { full: 'Centre d\'Impôts des Moyennes Entreprises Ngaoundéré', gender: 'm' },
    'cime kribi': { full: 'Centre d\'Impôts des Moyennes Entreprises Kribi', gender: 'm' },
    'cime littoral exterieur': { full: 'Centre d\'Impôts des Moyennes Entreprises Littoral Extérieur', gender: 'm' },
    'cime akwa 1': { full: 'Centre d\'Impôts des Moyennes Entreprises Akwa 1', gender: 'm' },
    'cime akwa 2': { full: 'Centre d\'Impôts des Moyennes Entreprises Akwa 2', gender: 'm' },
    'cime centre exterieur': { full: 'Centre d\'Impôts des Moyennes Entreprises Centre Extérieur', gender: 'm' },
    'cime bonanjo': { full: 'Centre d\'Impôts des Moyennes Entreprises Bonanjo', gender: 'm' },
    'cime yde est': { full: 'Centre d\'Impôts des Moyennes Entreprises Yaoundé Est', gender: 'm' },
    'cime yde ouest': { full: 'Centre d\'Impôts des Moyennes Entreprises Yaoundé Ouest', gender: 'm' },
    'cime maroua': { full: 'Centre d\'Impôts des Moyennes Entreprises Maroua', gender: 'm' },
    'cime garoua': { full: 'Centre d\'Impôts des Moyennes Entreprises Garoua', gender: 'm' },
    'cime bafoussam': { full: 'Centre d\'Impôts des Moyennes Entreprises Bafoussam', gender: 'm' },
    'cime bamenda': { full: 'Centre d\'Impôts des Moyennes Entreprises Bamenda', gender: 'm' },
    'cime bertoua': { full: 'Centre d\'Impôts des Moyennes Entreprises Bertoua', gender: 'm' },
    
    // === CENTRES SPÉCIALISÉS (Masculins) ===
    'cspli': { full: 'Centre Spécialisé des Professions Libérales et des Investissements', gender: 'm' },
    'cspli wouri': { full: 'Centre Spécialisé des Professions Libérales et des Investissements Wouri', gender: 'm' },
    'cspli mfoundi': { full: 'Centre Spécialisé des Professions Libérales et des Investissements Mfoundi', gender: 'm' },
    
    // === CELLULES DE GESTION SECTORIELLES (CGS) - Féminines ===
    'cgs': { full: 'Cellule de Gestion Sectorielle', gender: 'f' },
    'cgs industries': { full: 'Cellule de Gestion Sectorielle Industries', gender: 'f' },
    'cgs banques assurances': { full: 'Cellule de Gestion Sectorielle Banques, Assurances', gender: 'f' },
    'cgs services': { full: 'Cellule de Gestion Sectorielle Services', gender: 'f' },
    'cgs commerce general': { full: 'Cellule de Gestion Sectorielle Commerce Général', gender: 'f' },
    'cgs foret eau petrole': { full: 'Cellule de Gestion Sectorielle Forêt, Eau, Pétrole', gender: 'f' },
    
    // === BRIGADES DE CONTRÔLE ET VÉRIFICATION (BCV/BRE) - Féminines ===
    'bcv': { full: 'Brigade de Contrôle et Vérification', gender: 'f' },
    'bcv services': { full: 'Brigade de Contrôle et Vérification Services', gender: 'f' },
    'bcv banques assurances': { full: 'Brigade de Contrôle et Vérification Banques, Assurances', gender: 'f' },
    'bcv industries': { full: 'Brigade de Contrôle et Vérification Industries', gender: 'f' },
    'bcv commerce general': { full: 'Brigade de Contrôle et Vérification Commerce Général', gender: 'f' },
    'bcv foret eau petrole': { full: 'Brigade de Contrôle et Vérification Forêt, Eau, Pétrole', gender: 'f' },
    'bre': { full: 'Brigade des Enquêtes', gender: 'f' },
    'brcv': { full: 'Brigade de Recouvrement et de Contrôle des Valeurs', gender: 'f' },
    'brigade': { full: 'Brigade', gender: 'f' },
    
    // === SERVICES ADMINISTRATIFS DE GESTION (SAG) - Masculins ===
    'sag': { full: 'Service Administratif de Gestion', gender: 'm' },
    
    // === INSPECTION RÉGIONALE DES SERVICES (IRS) - Féminine ===
    'irs': { full: 'Inspection Régionale des Services', gender: 'f' },
    
    // === RECETTES RÉGIONALES DES IMPÔTS (RRI) - Féminine ===
    'rri': { full: 'Recette Régionale des Impôts', gender: 'f' },
    
    // === CELLULES RÉGIONALES DES PROGRAMMES DE SÉCURISATION (CRPSCV) - Féminines ===
    'crpscv': { full: 'Cellule Régionale des Programmes de Sécurisation et de Contrôle des Valeurs', gender: 'f' },
    
    // === CELLULES SPÉCIALISÉES D'IMMATRICULATION ET DE CONTRÔLE (CSICGI) - Féminines ===
    'csicgi': { full: 'Cellule Spécialisée d\'Immatriculation et de Contrôle des Grandes et Moyennes Imprimeries', gender: 'f' },
    
    // === CELLULES FISCALES DES ENTREPRISES (CFCE) - Féminines ===
    'cfce': { full: 'Cellule Fiscale des Grandes Entreprises', gender: 'f' },
    
    // === CELLULES SECTORIELLES D'EXPLOITATION (CSE) - Féminines ===
    'cse': { full: 'Cellule Sectorielle d\'Exploitation', gender: 'f' },
    
    // === CENTRES DE CONTRÔLE ET D'ÉCHANGE (CCX) - Masculins ===
    'ccx': { full: 'Centre de Contrôle et d\'Échange', gender: 'm' },
    
    // === CABINETS RÉGIONAUX (CAB) - Masculins ===
    'cab': { full: 'Cabinet', gender: 'm' },
    'cab dge': { full: 'Cabinet Direction des Grandes Entreprises', gender: 'm' },
    'cab dag': { full: 'Cabinet Direction des Affaires Générales', gender: 'm' },
    'cab drvfc': { full: 'Cabinet Direction du Recouvrement', gender: 'm' },
    'cab dlrfi': { full: 'Cabinet Division de la Législation', gender: 'm' },
    'cab dcx': { full: 'Cabinet Division du Contentieux', gender: 'm' },
    'cab di': { full: 'Cabinet Division de l\'Informatique', gender: 'm' },
    'cab dssi': { full: 'Cabinet Division des Statistiques', gender: 'm' },
    'cab depscf': { full: 'Cabinet Division des Enquêtes', gender: 'm' },
    'cab minfi': { full: 'Cabinet Ministère des Finances', gender: 'm' },
    
    // === CENTRES RÉGIONAUX DES IMPÔTS (CRI) - Masculins ===
    'cric1': { full: 'Centre Régional des Impôts du Centre 1', gender: 'm' },
    'cric2': { full: 'Centre Régional des Impôts du Centre 2', gender: 'm' },
    'cric ext': { full: 'Centre Régional des Impôts du Centre Extérieur', gender: 'm' },
    'cric-ext': { full: 'Centre Régional des Impôts du Centre Extérieur', gender: 'm' },
    'cril1': { full: 'Centre Régional des Impôts du Littoral 1', gender: 'm' },
    'cril2': { full: 'Centre Régional des Impôts du Littoral 2', gender: 'm' },
    'cril ext': { full: 'Centre Régional des Impôts du Littoral Extérieur', gender: 'm' },
    'cril-ext': { full: 'Centre Régional des Impôts du Littoral Extérieur', gender: 'm' },
    'cris': { full: 'Centre Régional des Impôts du Sud', gender: 'm' },
    'crisw': { full: 'Centre Régional des Impôts du Sud-Ouest', gender: 'm' },
    'crin': { full: 'Centre Régional des Impôts du Nord', gender: 'm' },
    'crinw': { full: 'Centre Régional des Impôts du Nord-Ouest', gender: 'm' },
    'crio': { full: 'Centre Régional des Impôts de l\'Ouest', gender: 'm' },
    'crie': { full: 'Centre Régional des Impôts de l\'Est', gender: 'm' },
    'cria': { full: 'Centre Régional des Impôts de l\'Adamaoua', gender: 'm' },
    'crien': { full: 'Centre Régional des Impôts de l\'Extrême-Nord', gender: 'm' },
    'criso': { full: 'Centre Régional des Impôts du Sud-Ouest', gender: 'm' },
    'crino': { full: 'Centre Régional des Impôts du Nord-Ouest', gender: 'm' },
    'cri': { full: 'Centre Régional des Impôts', gender: 'm' },
    'centre': { full: 'Centre', gender: 'm' },
    
    // === DIRECTIONS (Féminines) ===
    'dge': { full: 'Direction des Grandes Entreprises', gender: 'f' },
    'dag': { full: 'Direction des Affaires Générales', gender: 'f' },
    'drvfc': { full: 'Direction du Recouvrement, des Valeurs Fiscales et de la Curatelle', gender: 'f' },
    'drh': { full: 'Direction des Ressources Humaines', gender: 'f' },
    'dgi': { full: 'Direction Générale des Impôts', gender: 'f' },
    'dgb': { full: 'Direction Générale du Budget', gender: 'f' },
    'dgtcfm': { full: 'Direction Générale du Trésor et de la Coopération Financière et Monétaire', gender: 'f' },
    'direction': { full: 'Direction', gender: 'f' },
    'dir': { full: 'Direction', gender: 'f' },
    
    // === SOUS-DIRECTIONS (Féminines) ===
    'sous-direction': { full: 'Sous-Direction', gender: 'f' },
    'sous-direction du personnel': { full: 'Sous-Direction du Personnel', gender: 'f' },
    'sous-direction du budget et du materiel': { full: 'Sous-Direction du Budget et du Matériel', gender: 'f' },
    'sous-direction du recouvrement': { full: 'Sous-Direction du Recouvrement', gender: 'f' },
    'sous-direction des valeurs fiscales': { full: 'Sous-Direction des Valeurs Fiscales', gender: 'f' },
    'sous-direction de la curatelle': { full: 'Sous-Direction de la Curatelle', gender: 'f' },
    'sous-direction du suivi des recettes affectees': { full: 'Sous-Direction du Suivi des Recettes Affectées', gender: 'f' },
    
    // === DIVISIONS (Féminines) ===
    'depscf': { full: 'Division des Enquêtes, de la Programmation et du Suivi du Contrôle Fiscal', gender: 'f' },
    'deprf': { full: 'Division des Études de la Planification et des Réformes Fiscales', gender: 'f' },
    'dc': { full: 'Division du Contentieux', gender: 'f' },
    'dcont': { full: 'Division du Contentieux', gender: 'f' },
    'di': { full: 'Division de l\'Informatique', gender: 'f' },
    'dinf': { full: 'Division de l\'Informatique', gender: 'f' },
    'dlrfi': { full: 'Division de la Législation et des Relations Fiscales Internationales', gender: 'f' },
    'dssi': { full: 'Division des Statistiques, des Simulations et de l\'Immatriculation', gender: 'f' },
    'daj': { full: 'Division des Affaires Juridiques', gender: 'f' },
    'div': { full: 'Division', gender: 'f' },
    'division': { full: 'Division', gender: 'f' },
    
    // === CELLULES SPÉCIALISÉES (Féminines) ===
    'cic': { full: 'Cellule de l\'Information et de la Communication', gender: 'f' },
    'cpfc': { full: 'Cellule du Perfectionnement et de la Formation Continue', gender: 'f' },
    'cex': { full: 'Cellule de l\'Exploitation', gender: 'f' },
    'cis': { full: 'Cellule de l\'Informatique et des Statistiques', gender: 'f' },
    'csrfds': { full: 'Cellule du Suivi de Régimes Fiscaux Dérogatoires et Spéciaux', gender: 'f' },
    'clf': { full: 'Cellule de la Législation Fiscale', gender: 'f' },
    'ccf': { full: 'Cellule du Contentieux Fiscal', gender: 'f' },
    'crri': { full: 'Cellule des Remboursements et Restitutions d\'Impôts', gender: 'f' },
    'crc': { full: 'Cellule des Réseaux de Communication', gender: 'f' },
    'cimm': { full: 'Cellule de l\'Immatriculation', gender: 'f' },
    'craif': { full: 'Cellule de Recherche et d\'Analyse des Informations Fiscales', gender: 'f' },
    'cps': { full: 'Cellule de la Programmation et du Suivi', gender: 'f' },
    'csarg': { full: 'Cellule du Suivi, des Analyses et des Recours Gracieux', gender: 'f' },
    'crfi': { full: 'Cellule des Relations Fiscales Internationales', gender: 'f' },
    'crif': { full: 'Cellule de la Répression des Infractions Fiscales', gender: 'f' },
    'css': { full: 'Cellule des Statistiques et des Simulations', gender: 'f' },
    'cgs dge': { full: 'Cellule de Gestion et du Suivi DGE', gender: 'f' },
    'ccx dge': { full: 'Cellule du Contentieux DGE', gender: 'f' },
    'cell': { full: 'Cellule', gender: 'f' },
    'cellule': { full: 'Cellule', gender: 'f' },
    
    // === PROGRAMMES DE SÉCURISATION (Masculins) ===
    'psr': { full: 'Programme de Sécurisation des Recettes', gender: 'm' },
    'psrr': { full: 'Programme de Sécurisation des Recettes Routières', gender: 'm' },
    'psrf': { full: 'Programme de Sécurisation des Recettes Forestières', gender: 'm' },
    'psrep': { full: 'Programme de Sécurisation des Recettes de l\'Élevage et des Pêches', gender: 'm' },
    'psrmee': { full: 'Programme de Sécurisation des Recettes Minières, de l\'Eau et de l\'Énergie', gender: 'm' },
    'psrdcf': { full: 'Programme de Sécurisation des Recettes Domaniales, Cadastrales et Foncières', gender: 'm' },
    'programme': { full: 'Programme', gender: 'm' },
    
    // === INSPECTION (Féminine) ===
    'isi': { full: 'Inspection des Services des Impôts', gender: 'f' },
    'igsrf': { full: 'Inspection Générale des Services des Régies Financières', gender: 'f' },
    'insp': { full: 'Inspection', gender: 'f' },
    'inspection': { full: 'Inspection', gender: 'f' },
    
    // === SERVICES (Masculins) ===
    'so': { full: 'Service d\'Ordre', gender: 'm' },
    'spm': { full: 'Services du Premier Ministre', gender: 'm' },
    'sie': { full: 'Service de l\'Information des Entreprises', gender: 'm' },
    'sca': { full: 'Service du Courrier et des Archives', gender: 'm' },
    'sm': { full: 'Service de la Maintenance', gender: 'm' },
    'servcom': { full: 'Service de la Communication', gender: 'm' },
    'srv': { full: 'Service', gender: 'm' },
    'service': { full: 'Service', gender: 'm' },
    
    // === CONTRÔLE (Masculin) ===
    'cse': { full: 'Contrôle Supérieur de l\'État', gender: 'm' },
    'controle': { full: 'Contrôle', gender: 'm' },
    'contrôle': { full: 'Contrôle', gender: 'm' },
    
    // === SECRÉTARIAT (Masculin) ===
    'sg/prc': { full: 'Secrétariat Général/PRC', gender: 'm' },
    'sg/minfi': { full: 'Secrétariat Général MINFI', gender: 'm' },
    'sg': { full: 'Secrétariat Général', gender: 'm' },
    'secr': { full: 'Secrétariat', gender: 'm' },
    'secrétariat': { full: 'Secrétariat', gender: 'm' },
    
    // === DÉLÉGATION (Féminine) ===
    'dgsn': { full: 'Délégation Générale à la Sûreté Nationale', gender: 'f' },
    'deleg': { full: 'Délégation', gender: 'f' },
    'délégation': { full: 'Délégation', gender: 'f' },
    
    // === MINISTÈRES (Masculins) ===
    'minfi': { full: 'Ministère des Finances', gender: 'm' },
    'minat': { full: 'Ministère de l\'Administration Territoriale', gender: 'm' },
    'minsante': { full: 'Ministère de la Santé Publique', gender: 'm' },
    'minepat': { full: 'Ministère de l\'Économie, de la Planification et de l\'Aménagement du Territoire', gender: 'm' },
    'mindcaf': { full: 'Ministère des Domaines, du Cadastre et des Affaires Foncières', gender: 'm' },
    'minddevel': { full: 'Ministère de la Décentralisation et du Développement Local', gender: 'm' },
    'mincommerce': { full: 'Ministère du Commerce', gender: 'm' },
    'minminidt': { full: 'Ministère de l\'Industrie, des Mines et du Développement Technologique', gender: 'm' },
    'minee': { full: 'Ministère de l\'Eau et de l\'Énergie', gender: 'm' },
    'mintransport': { full: 'Ministère des Transports', gender: 'm' },
    'minpostel': { full: 'Ministère des Postes et Télécommunications', gender: 'm' },
    'minefop': { full: 'Ministère de l\'Emploi et de la Formation Professionnelle', gender: 'm' },
    'minesup': { full: 'Ministère de l\'Enseignement Supérieur et de la Recherche', gender: 'm' },
    'minproff': { full: 'Ministère de la Promotion de la Femme et de la Famille', gender: 'm' },
    'minader': { full: 'Ministère de l\'Agriculture et du Développement Rural', gender: 'm' },
    'minfof': { full: 'Ministère des Forêts et de la Faune', gender: 'm' },
    'mincom': { full: 'Ministère de la Communication', gender: 'm' },
    'minpmeesa': { full: 'Ministère des Petites et Moyennes Entreprises, de l\'Économie Sociale et de l\'Artisanat', gender: 'm' },
    'minmap': { full: 'Ministère Délégué à la Présidence chargé des Marchés Publics', gender: 'm' },
    'ministere': { full: 'Ministère', gender: 'm' },
    'ministère': { full: 'Ministère', gender: 'm' },
    
    // === ORGANISMES ET ENTREPRISES ===
    'elecam': { full: 'Elections Cameroon', gender: 'f' },
    'sonara': { full: 'Société Nationale de Raffinage', gender: 'f' },
    'camwater': { full: 'Cameroon Water Corporation', gender: 'f' },
    'camtel': { full: 'Cameroon Telecommunications', gender: 'f' },
    'feicom': { full: 'Fonds Spécial d\'Équipement et d\'Intervention Intercommunale', gender: 'm' },
    'caa': { full: 'Caisse Autonome d\'Amortissement', gender: 'f' },
    'cdc': { full: 'Caisse des Dépôts et Consignations', gender: 'f' },
    'cf': { full: 'Crédit Foncier', gender: 'm' },
    'ctrep': { full: 'Commission Technique de Réhabilitation des Entreprises Publiques', gender: 'f' },
    'anif': { full: 'Agence Nationale d\'Investigation Financière', gender: 'f' },
    'cuy': { full: 'Communauté Urbaine de Yaoundé', gender: 'f' },
    'crtv': { full: 'Cameroon Radio Television', gender: 'f' },
    'chraecrh': { full: 'Centre Hospitalier de Recherche et d\'Application en Chirurgie Endoscopique et Reproduction Humaine', gender: 'm' },
    'crso': { full: 'Conseil Régional du Sud-Ouest', gender: 'm' },
    
    // === AUTRES STRUCTURES ===
    // Masculins
    'cat': { full: 'Centre d\'Appels Téléphoniques', gender: 'm' },
    'ri': { full: 'Responsable Informatique', gender: 'm' },
    'bur': { full: 'Bureau', gender: 'm' },
    'bureau': { full: 'Bureau', gender: 'm' },
    'dept': { full: 'Département', gender: 'm' },
    'dpt': { full: 'Département', gender: 'm' },
    'département': { full: 'Département', gender: 'm' },
    'sect': { full: 'Secteur', gender: 'm' },
    'secteur': { full: 'Secteur', gender: 'm' },
    'pole': { full: 'Pôle', gender: 'm' },
    'pôle': { full: 'Pôle', gender: 'm' },
    'comite': { full: 'Comité', gender: 'm' },
    'comité': { full: 'Comité', gender: 'm' },
    'conseil': { full: 'Conseil', gender: 'm' },
    'guichet': { full: 'Guichet', gender: 'm' },
    'audit': { full: 'Audit', gender: 'm' },
    'ueir': { full: 'Unité d\'Échange International des Renseignements', gender: 'f' },
    
    // Féminins
    'unite': { full: 'Unité', gender: 'f' },
    'unité': { full: 'Unité', gender: 'f' },
    'brig': { full: 'Brigade', gender: 'f' },
    'sect.': { full: 'Section', gender: 'f' },
    'section': { full: 'Section', gender: 'f' },
    'ag': { full: 'Agence', gender: 'f' },
    'agence': { full: 'Agence', gender: 'f' },
    'ant': { full: 'Antenne', gender: 'f' },
    'antenne': { full: 'Antenne', gender: 'f' },
    's/dir': { full: 'Sous-Direction', gender: 'f' },
    'sdir': { full: 'Sous-Direction', gender: 'f' },
    'bibliotheque': { full: 'Bibliothèque', gender: 'f' },
    'coordination': { full: 'Coordination', gender: 'f' },
    'comptabilite': { full: 'Comptabilité', gender: 'f' },
    'comptabilité': { full: 'Comptabilité', gender: 'f' },
    'accueil': { full: 'Accueil et Orientation', gender: 'm' },
    
    // === STRUCTURES AVEC SIGLE CSI/EPA ===
    'csi/epa': { full: 'Cellule Spécialisée d\'Immatriculation des Établissements Publics et Assimilés', gender: 'f' },
    
    // === AVEC POINTS (FORMAT ADMINISTRATIF) ===
    'd.g.i': { full: 'Direction Générale des Impôts', gender: 'f' },
    'd.g.i.': { full: 'Direction Générale des Impôts', gender: 'f' },
    'd.a.g': { full: 'Direction des Affaires Générales', gender: 'f' },
    'd.a.g.': { full: 'Direction des Affaires Générales', gender: 'f' },
    'c.r.i': { full: 'Centre Régional des Impôts', gender: 'm' },
    'c.r.i.': { full: 'Centre Régional des Impôts', gender: 'm' },
    'd.g.e': { full: 'Direction des Grandes Entreprises', gender: 'f' },
    'd.g.e.': { full: 'Direction des Grandes Entreprises', gender: 'f' },
    'd.r.h': { full: 'Direction des Ressources Humaines', gender: 'f' },
    'd.r.h.': { full: 'Direction des Ressources Humaines', gender: 'f' },
    's.r.h': { full: 'Service des Ressources Humaines', gender: 'm' },
    's.r.h.': { full: 'Service des Ressources Humaines', gender: 'm' },
    'c.i': { full: 'Centre des Impôts', gender: 'm' },
    'c.i.': { full: 'Centre des Impôts', gender: 'm' },
    'd.r.v.f.c': { full: 'Direction du Recouvrement, des Valeurs Fiscales et de la Curatelle', gender: 'f' },
    'd.r.v.f.c.': { full: 'Direction du Recouvrement, des Valeurs Fiscales et de la Curatelle', gender: 'f' },
    'i.s.i': { full: 'Inspection des Services des Impôts', gender: 'f' },
    'i.s.i.': { full: 'Inspection des Services des Impôts', gender: 'f' },
    'c.s.e': { full: 'Contrôle Supérieur de l\'État', gender: 'm' },
    'c.s.e.': { full: 'Contrôle Supérieur de l\'État', gender: 'm' },
    's.o': { full: 'Service d\'Ordre', gender: 'm' },
    's.o.': { full: 'Service d\'Ordre', gender: 'm' },
    'c.i.c': { full: 'Cellule de l\'Information et de la Communication', gender: 'f' },
    'c.i.c.': { full: 'Cellule de l\'Information et de la Communication', gender: 'f' },
    
    // === VARIANTES AVEC CASSE DIFFÉRENTE (MAJUSCULES) ===
    'CDI': { full: 'Centre d\'Impôts Départemental', gender: 'm' },
    'CIME': { full: 'Centre d\'Impôts des Moyennes Entreprises', gender: 'm' },
    'CSPLI': { full: 'Centre Spécialisé des Professions Libérales et des Investissements', gender: 'm' },
    'CRI': { full: 'Centre Régional des Impôts', gender: 'm' },
    'DGE': { full: 'Direction des Grandes Entreprises', gender: 'f' },
    'DAG': { full: 'Direction des Affaires Générales', gender: 'f' },
    'DGI': { full: 'Direction Générale des Impôts', gender: 'f' },
    'DGB': { full: 'Direction Générale du Budget', gender: 'f' },
    'MINFI': { full: 'Ministère des Finances', gender: 'm' },
    'CAB': { full: 'Cabinet', gender: 'm' },
    'ISI': { full: 'Inspection des Services des Impôts', gender: 'f' },
    'CSE': { full: 'Contrôle Supérieur de l\'État', gender: 'm' },
    'CIC': { full: 'Cellule de l\'Information et de la Communication', gender: 'f' },
    'CPFC': { full: 'Cellule du Perfectionnement et de la Formation Continue', gender: 'f' },
    'DRVFC': { full: 'Direction du Recouvrement, des Valeurs Fiscales et de la Curatelle', gender: 'f' },
    'DEPSCF': { full: 'Division des Enquêtes, de la Programmation et du Suivi du Contrôle Fiscal', gender: 'f' },
    'DEPRF': { full: 'Division des Études de la Planification et des Réformes Fiscales', gender: 'f' },
    'DINF': { full: 'Division de l\'Informatique', gender: 'f' },
    'DCONT': { full: 'Division du Contentieux', gender: 'f' },
    'DLRFI': { full: 'Division de la Législation et des Relations Fiscales Internationales', gender: 'f' },
    'DSSI': { full: 'Division des Statistiques, des Simulations et de l\'Immatriculation', gender: 'f' },
    'PSRR': { full: 'Programme de Sécurisation des Recettes Routières', gender: 'm' },
    'PSRF': { full: 'Programme de Sécurisation des Recettes Forestières', gender: 'm' },
    'PSREP': { full: 'Programme de Sécurisation des Recettes de l\'Élevage et des Pêches', gender: 'm' },
    'PSRMEE': { full: 'Programme de Sécurisation des Recettes Minières, de l\'Eau et de l\'Énergie', gender: 'm' },
    'PSRDCF': { full: 'Programme de Sécurisation des Recettes Domaniales, Cadastrales et Foncières', gender: 'm' },
    'SO': { full: 'Service d\'Ordre', gender: 'm' },
    'SPM': { full: 'Services du Premier Ministre', gender: 'm' },
    'DGSN': { full: 'Délégation Générale à la Sûreté Nationale', gender: 'f' },
    'ELECAM': { full: 'Elections Cameroon', gender: 'f' },
    'SONARA': { full: 'Société Nationale de Raffinage', gender: 'f' },
    'CAMWATER': { full: 'Cameroon Water Corporation', gender: 'f' },
    'CAMTEL': { full: 'Cameroon Telecommunications', gender: 'f' },
    'FEICOM': { full: 'Fonds Spécial d\'Équipement et d\'Intervention Intercommunale', gender: 'm' },
    'CGS': { full: 'Cellule de Gestion Sectorielle', gender: 'f' },
    'BCV': { full: 'Brigade de Contrôle et Vérification', gender: 'f' },
    'BRE': { full: 'Brigade des Enquêtes', gender: 'f' },
    'SAG': { full: 'Service Administratif de Gestion', gender: 'm' },
    'IRS': { full: 'Inspection Régionale des Services', gender: 'f' },
    'RRI': { full: 'Recette Régionale des Impôts', gender: 'f' },
    'CRPSCV': { full: 'Cellule Régionale des Programmes de Sécurisation et de Contrôle des Valeurs', gender: 'f' },
    'CSICGI': { full: 'Cellule Spécialisée d\'Immatriculation et de Contrôle des Grandes et Moyennes Imprimeries', gender: 'f' },
    'CFCE': { full: 'Cellule Fiscale des Grandes Entreprises', gender: 'f' },
    'CCX': { full: 'Centre de Contrôle et d\'Échange', gender: 'm' },
    'DRH': { full: 'Direction des Ressources Humaines', gender: 'f' }
};

export default abbreviations;